apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-slave
spec:
  template:
    spec:
      containers:
      - name: redis
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "1000m"