apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-admin
  labels:
    app.kubernetes.io/name: pg-admin
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pg-admin
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pg-admin
        app.kubernetes.io/component: web
    spec:
      securityContext:
        fsGroup: 5050
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: pg-admin
          image: dpage/pgadmin4:8.13
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PGADMIN_LISTEN_PORT
              value: "8080"
            - name: PGADMIN_SERVER_JSON_FILE
              value: "/pgadmin4/servers.json"
            - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
              value: "True"
            - name: PGADMIN_CONFIG_LOGIN_BANNER
              value: "MinCloud PostgreSQL Admin"
            - name: PGADMIN_DISABLE_POSTFIX
              value: "true"
          envFrom:
            - secretRef:
                name: pg-admin-secret
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgadmin
            - name: servers
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
          livenessProbe:
            httpGet:
              path: /misc/ping
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /misc/ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 512Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pg-admin-data
        - name: servers
          configMap:
            name: pg-admin-servers
