apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-admin-data
  labels:
    app.kubernetes.io/name: pg-admin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
