apiVersion: v1
kind: Service
metadata:
  name: pg-admin
  labels:
    app.kubernetes.io/name: pg-admin
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: pg-admin
    app.kubernetes.io/component: web
