apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: message-broker

data:
  rabbitmq.conf: |
    # Clustering
    cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc
    cluster_formation.k8s.address_type = hostname
    cluster_partition_handling = pause_minority

    # Networking
    listeners.tcp.default = 5672
    management.listener.port = 15672

    # Auth
    default_user = ${RABBITMQ_DEFAULT_USER}
    default_pass = ${RABBITMQ_DEFAULT_PASS}

    # Limits
    vm_memory_high_watermark.relative = 0.6

  enabled_plugins: |
    [rabbitmq_management].
