apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: broker
spec:
  replicas: 3
  image: rabbitmq:4.1.4-management
  persistence:
    storageClassName: ""
    storage: 10Gi
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  service:
    type: ClusterIP
  rabbitmq:
    additionalConfig: |
      cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
      cluster_formation.k8s.address_type = hostname
      cluster_partition_handling = pause_minority
      disk_free_limit.absolute = 2GB
      vm_memory_high_watermark.relative = 0.55
  override:
    service:
      metadata:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "15692"
          prometheus.io/path: "/metrics"
