apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: message-broker

type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "change-me"
  RABBITMQ_ERLANG_COOKIE: "CHANGE_ME_COOKIE_32CHARS_MINIMUM"
