apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: message-broker
spec:
  type: ClusterIP
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  selector:
    app.kubernetes.io/name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: message-broker
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: epmd
      port: 4369
      targetPort: 4369
    - name: dist
      port: 25672
      targetPort: 25672
  selector:
    app.kubernetes.io/name: rabbitmq
