apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../base
   - ingress.yaml

namePrefix: staging-

commonLabels:
  environment: staging

patches:
  - path: secret-patch.yaml
  - path: servers-patch.yaml
