apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../base
  - ingress.yaml

namePrefix: staging-

labels:
  - includeSelectors: true
    pairs:
      environment: staging
      app.kubernetes.io/part-of: pg-admin

patches:
  - path: secret-patch.yaml
  - path: servers-patch.yaml
