apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../base
  - application.yaml

patchesStrategicMerge:
  - rabbitmq-patch.yaml
  - rabbitmq-secret-patch.yaml

commonLabels:
  environment: staging
