apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  labels:
    environment: staging
stringData:
  RABBITMQ_DEFAULT_USER: "staging-user"
  RABBITMQ_DEFAULT_PASS: "staging-password-change-me"
  RABBITMQ_ERLANG_COOKIE: "STAGING_CHANGE_ME_COOKIE_32CHARS_MINIMUM"
