apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: database
data:
  redis-master.conf: |
    # Redis Master Configuration
    bind 0.0.0.0
    port 6379
    
    # Persistence
    save 900 1
    save 300 10
    save 60 10000
    
    # Replication
    # masterauth will be set by init container if auth is enabled
    
    # Security
    protected-mode no
    
    # Performance
    tcp-keepalive 60
    timeout 0
    
    # Logging
    loglevel notice
    
  redis-slave.conf: |
    # Redis Slave Configuration
    bind 0.0.0.0
    port 6379
    
    # Persistence
    save 900 1
    save 300 10
    save 60 10000
    
    # Replication
    # replicaof will be set by init container
    replica-read-only yes
    
    # Security
    protected-mode no
    
    # Performance
    tcp-keepalive 60
    timeout 0
    
    # Logging
    loglevel notice