apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    app.kubernetes.io/name: redis-master
    role: master
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: redis
    app.kubernetes.io/name: redis-master
    role: master
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master-headless
  labels:
    app: redis
    app.kubernetes.io/name: redis-master
    role: master
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: redis
    app.kubernetes.io/name: redis-master
    role: master
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    app.kubernetes.io/name: redis-slave
    role: slave
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: redis
    app.kubernetes.io/name: redis-slave
    role: slave
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  labels:
    app: redis-sentinel
    app.kubernetes.io/name: redis-sentinel
spec:
  type: ClusterIP
  ports:
    - port: 26379
      targetPort: 26379
      name: sentinel
  selector:
    app: redis-sentinel
    app.kubernetes.io/name: redis-sentinel
---
# Service for applications to connect to Redis (reads from slaves, writes to master via sentinel)
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    app.kubernetes.io/name: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
    - port: 26379
      targetPort: 26379
      name: sentinel
  selector:
    app: redis-sentinel
    app.kubernetes.io/name: redis-sentinel
