apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Postgres Primary",
          "Group": "Default",
          "Host": "postgres-write",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "SSLMode": "prefer",
          "Username": "postgres"
        },
        "2": {
          "Name": "Postgres Read",
          "Group": "Default",
          "Host": "postgres-read",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "SSLMode": "prefer",
          "Username": "postgres"
        }
      }
    }
