apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pgadmin
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pgadmin
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PGADMIN_LISTEN_PORT
              value: "8080"
            - name: PGADMIN_SERVER_JSON_FILE
              value: "/pgadmin4/servers.json"
            - name: PGADMIN_DISABLE_POSTFIX
              value: "true"
          envFrom:
            - secretRef:
                name: pgadmin-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgadmin
            # - name: servers
            #   mountPath: /pgadmin4/servers.json
            #   subPath: servers.json
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 512Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pgadmin-data
        - name: servers
          configMap:
            name: pgadmin-servers
