apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: pgadmin

resources:
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: pgadmin
      app.kubernetes.io/component: web
      app.kubernetes.io/part-of: postgres

namePrefix: ""

namespace: ""
