apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-data
  labels:
    app.kubernetes.io/name: pgadmin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
