apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:admin, applications, create, */*, allow
    p, role:admin, applications, delete, */*, allow
    p, role:admin, applications, get, */*, allow
    p, role:admin, applications, override, */*, allow
    p, role:admin, applications, sync, */*, allow
    p, role:admin, applications, update, */*, allow
  policy.default: role:readonly
