apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-replica
spec:
  template:
    spec:
      containers:
      - name: postgres
        env:
        - name: PRIMARY_SERVICE_NAME
          value: "staging-postgres-primary"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: replica
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi