apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-replica
spec:
  template:
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-replica-data
      containers:
      - name: postgres
        env:
        - name: PRIMARY_SERVICE_NAME
          value: "staging-postgres-primary"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
