apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-primary
spec:
  template:
    spec:
      containers:
      - name: postgres
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      resources:
        requests:
          storage: 10Gi
