apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  postgres-user: "postgres"
  postgres-password: "staging-password-change-me"
  replication-password: "staging-replication-password-change-me"
