apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-replica-data
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: replica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
