apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-primary-data
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: primary
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
